### ISSUE TITLE
Add yaml load of scoreboard output HTML locations

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#172]
**Is your feature request related to a problem?** 

During a contest/test on 2/13/2021 the scoreboard settings for
- Output HTML dir for Judges
- Output Public HTML dir

Updates for those fields had to be done manually using the Admin 
Configure Contest -> Settings -> Edit Scoring Properties

**Have you considered other ways to accomplish the same thing?** 

Yes, this is a way to automate the setting instead of requiring
someone to remember 

**Feature Description**:

Automate the load of these settings if present in yaml.
- Output HTML dir for Judges
- Output Public HTML dir

When contest.yaml is exported add these fields.

**Additional context**:

none.

**Comment by lane55** [comment]
Name for Output HTML dir for Judges is: 
   output_private_score_dir
Output Public HTML dir is:
   output_public_score_dir

**Comment by lane55** [comment]
# default values/example
output_private_score_dir: html
output_public_score_dir: public_html

# from a 2/13/2021 contest, used:
output_private_score_dir: /home/ubuntu/pc2/6169/projects/WebTeamInterface-1.1/WebContent/WTI-UI/supersecret
output_public_score_dir: /home/ubuntu/pc2/6169/projects/WebTeamInterface-1.1/WebContent/WTI-UI/scoreboard

**Comment by clevengr** [comment]
This issue was fixed in PR #176.  However, the comment/description in that PR did not include any [GitHub Closing Keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) -- it simply contained "172" in the "Issue which the PR fixes" section.  In order to invoke "automatic closure" you have to precede the Issue number with one of the "closing" keywords (like "closes" or "fixes") and a `#` character.

Closing the issue manually.
