### ISSUE TITLE
Remove account

### ISSUE THREAD

**Issue by XuPuPG** [pc2ccs/pc2v9#228]
Sometimes the ability to disable or delete a member's account is missing.
In pc ^ 2 administrator, on the Accounts tab, add a remove button, which will delete the selected account and disconnect this user, or mark him as deleted without deleting the information associated with him (attempts, questions) while preventing him from logging into the account with the error "account deleted "
To do this, the administrator had to change the account password.

**Comment by clevengr** [comment]
The ability to disable an account already exists:  in the Admin "Accounts" tab, select the account, then uncheck "Login" in the "Permisssions/Abilities" list.  This will prohibit an account from being able to login, without the need to change the password.  

The ability to "force logoff" an account also exists: on the Server GUI, select the logged in account and click "Logoff".

As to the ability to DELETE an account, we can put that on the list of requested enhancements, but frankly we're not sure it's of much value -- especially since you're suggesting DELETING an account while still retaining the data (attempts, questions) associated with the account.  That pretty much means the account is NOT deleted...

**Comment by lane55** [comment]
If a goal is to remove a user login and disable login do the following:
1. Accounts - Edit the user's account, change their password
1. Logins - Logoff the user

If there are many users, use the Safe/Load Accounts feature to change their passwords
and/or remove their pc2 permission to login.

**Comment by lane55** [comment]
Accounts can be effectively be removed by removing the accounts
from any scoreboard and disabling the login as described in the April 11, 2021 comment.

Removing the account from the model "deleting" can potentially cause referential errors (Exceptions).
For example if the account has submitted runs, removing the account from the model could cause
an exception when printing reports about the run(s).

I recommend closing this issue.

**Comment by clevengr** [comment]
Closing the issue; the ability to disable logins and to suppress any account display information already exists, as described in the comments on the Issue.
