### ISSUE TITLE
single point of definition of .ans and .in files

### ISSUE THREAD

**Issue by XuPuPG** [pc2ccs/pc2v9#234]
**I do not quite understand why there is a need to specify question and answer files here if there can be more than one pair of them and they are still specified here**
![image](https://user-images.githubusercontent.com/11676369/114742783-bc7c2b80-9d54-11eb-9bcd-1016405d7eb9.png)
![image](https://user-images.githubusercontent.com/11676369/114742819-c736c080-9d54-11eb-94ce-617489b8b7ad.png)

**Comment by clevengr** [comment]
This is a legacy code issue.  Originally, PC2 allowed only a single input and answer file per problem (problems back then were typically written to require the submitted program to include a loop which processed each input data set as part of a single program execution, and answer files contained the output for ALL data sets in a single file).  Support for multiple input/answer files was added in a newer version.  However, our general policy is to retain 'backward-compatibility' when possible, so that users don't HAVE to use new things if they're happy with the old way things worked.  Hence, you can still use the single-file screen if you only have one file, or you can use the new "multiple data files" screen if you want to use multiple files.  We assume you noticed that if you use multiple data files it automatically populates the "single file" screen with the first of the multiple data files?
