### ISSUE TITLE
Provide a way to add sample data files to the test data files 

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#244]
**Is your feature request related to a problem?** 

When shadowing there is a step required to create test cases data files.
The sample files should be tested before the judge's data files (in secret/)

Here is the workaround:

Sample and Secret data files need to be renamed and 
after renaming the sample files are copied to the secret directory.

Merge the “sample data” into the “secret data” folder and load ALL data
files into PC2 (Kattis runs against both the samples and the secret data).
There is a Python3 script in the NAC GitHub repo that can be used to do
this;  it takes a single argument -- the name of the “cdp” folder which
contains the config folder which contains the problem package (problem
folders and a single “problem.yaml” file).  Warning:  the script MOVES
the sample data into the secret data folder, prepending “sample__”
to all sample data files and “secret__” to all secret data files.
This produces a single folder, “secret”, containing all the data files in
proper alphabetical order -- but it destroys the original cdp structure.

Explanatory note:  data files are required to be run in alphabetical
order, and Kattis runs all sample files before any secret files

Source: NADC 2021 PC2 Shadow Configuration Verification Checklist

**Feature Description**: 

Using --load (from yaml) automatically load sample files before loading secret files for each problem.

For work arround:

Copy sample files to data/secret directory, rename all data files so that the sample files will
be used before the secret files.

Copy each .in and .ans file from sample data directory  (config\<shortdirname>\data\sample) to secret directory
(config\<shortdirname>\data\secret) with a new name, the new file name should be the sample file name
prepended with sample__ .   Ex. data/sample/sumit.in copy to data/secret/sample__sumit.in

Rename all secret files, prepend secret_ to each secret__, ex data/secret/sumit4.ans to data/secret/secret__sumit4.ans

By default renames and copy files.
Provide two options: 
 - output a script to change files
 - list files to be changed and show counts of files to be created/renamed.

**Have you considered other ways to accomplish the same thing?** 

There are scripts to rename and copy samples into the secret directory

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?** 

Yes, create a new tool that will perform the renaming and copying.

**Additional context**:

**Comment by lane55** [comment]
The tool was a fill gap/work around.
The initial load yaml should load the samples into the problem.   Since the order
of the files will be assigned as the files are loaded, if the samples are loaded first
then the judges data files - that will meet the requirement that the samples be
tested before the judge's "secret" data.

**Comment by lane55** [comment]
Requirements:
- in yaml load, by default load sample data then judge's date.
- add a yaml name/value to NOT load the samples, name: do-not-load-sample-datafiles : true
   (default is false)

**Comment by lane55** [comment]
By default loads sample data, to not load in yaml use:
loadSampleJudgesData : false

**Comment by lane55** [comment]
Merged closing issue

**Comment by clevengr** [comment]
I do not at all understand the state of this Issue (nor the overall state of the situation with respect to loading sample/secret data files).  I'm unclear about the following:

- If this Issue is Closed (which it currently is), what does that mean with regard to the state of the problem which this Issue is supposed to be addressing?  In other words, there was originally a problem  --- specifically, the problem is that we need to support loading sample data files along with secret -- and this GitHub Issue was originally intended to address that.  Now, this issue is Closed... but it's not clear that it has addressed the original Issue (maybe it has; I'm saying "it's not clear whether it has"...)
- What is the meaning of the most recent comment, `Merged closing issue`?  I cannot parse what this means.
- What is the current status with respect to loading sample data files?
- What is the current state with regard to the default operation?  (That is, currently do samples GET loaded or NOT GET loaded?)
- How does this PR relate to loading sample data files when NOT using `--load`?   (That is, if we are supporting loading of sample data files via YAML, we need to have equivalent support when not using YAML -- i.e., when using the Admin>Configure>Problems>Edit>DataFiles tab.)

**Comment by lane55** [comment]
John,

                Current work state is:

                I 244 – was initial work which “loaded” sample data into model
                I 700 – change default action to not use/run code from 244
                I 701 – work to fix bug in 244.

                701 will fix the bug where Executable is looking for samples/ in the secret/
                directory, and should complete 244.

                I opened 701 rather than adding to 244 because 244 is merged and
                there is a choice about whether to track the bug or re-opening the
                original issue or create a discrete bug.  I chose the later.

Doug
