### ISSUE TITLE
Add support for per-problem memory limits and MLE judgement

### ISSUE THREAD

**Issue by clevengr** [pc2ccs/pc2v9#295]
**Feature Description**: 
Each contest problem should have a "memory limit" associated with it; when a submission for the problem is executed the system should enforce this memory limit in a manner similar to how it currently enforces a time limit. This would allow support for returning a "MLE" (Memory Limit Exceeded) submission result.

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?** 
- Add a "memory limit" field to class **core.model.Problem**.  Memory limit should probably be specified in MB (so a 2GB limit would be specified as "2048").
- Update the **Configure Contest > Settings** tab to allow specification of a contest-wide (global) memory limit (in MB).  This is the limit which will apply to any problem which does not explicitly set its own problem-specific limit.
- Update the **Configure Contest > Problems** tab to include display of the current memory limit for each problem.
- Update the **General** tab in the **EditProblemPane** class to support a new field, "Memory Limit (MB)".  The value in this field wil become the memory limit for the specified problem.
- Update the YAML loading routine(s) to support loading both a contest-wide and a problem-specific memory limit (in MB).
  - The contest-wide memory setting would appear in **contest.yaml** and should apply unless it is explicitly overridden by a memory limit in a specific **problem.yaml** file.
- Provide support for ability to specify an (OS-specific) _sandbox_ which is to be used to execute each test case of a submission.
  - The sandbox should enforce the problem-specified memory limit (and probably also the time limit) in an OS-specific way.
  - The sandbox should be user-selectable on a per-problem basis.

**Comment by lane55** [comment]
requirements change now both sandbox command and memory limit are per problem, in the problem.yaml file.
There is no global memory limit

**Comment by johnbrvc** [comment]
After doing some research on how to deal with MLE's in the PC2 sandbox, it seems there are 2 cases:
1) java and kotlin (kotlin is really java)
2) C++/C/Python

The 1st case is handled by the JVM and the "ulimit -d" method can not be used since java uses the same Linux address space as the code it is interpreting.   This can be (and already is) handled by the command lines options to the java execute command, namely, the  -Xmx### option, where ### is the maximum heap size for the JVM to allow for the user program.  Something like: -Xmx2048m would set the limit to 2GB.  

The 2nd case is handled by the "ulimit -d" in the sandbox script.  "ulimit -v" can not be used because that is the virtual memory size, which includes python itself and any packages (about 130MB just to start up without doing anything).  The "ulimit -d" measures only the data size which is about 50mb to start with, and users should know about including this in their memory usage.  As an example, if we use "ulimit -v 524288" and run a python program that allocates 4MB at a time, it runs out of memory at about 400MB using attached test program [memtest.txt](https://github.com/pc2ccs/pc2v9/files/10002943/memtest.txt):

```
96allocated
97allocated
98allocated
Traceback (most recent call last):
  File "memtest.py", line 7, in <module>
    a = array.array('i', (ii for ii in range (0,1024*1024)))
MemoryError
```
If we use "ulimit -d 524288", we get:

```
109allocated
110allocated
111allocated
112allocated
Traceback (most recent call last):
  File "memtest.py", line 7, in <module>
    a = array.array('i', (ii for ii in range (0,1024*1024)))
MemoryError
```

Which is much closer (about 450MB).  For Python, we can have a "python fudge-factor" to compensate for the memory used by python, but, I don't think that's necessary since people who use python should know there is inherent extra memory usage.

For C/C++ this is not an issue, and "ulimit -d 524288" works perfectly - again, "ulimit -v 524288" does NOT since it includes the entire VM footprint including the text segment and all libraries.  I do not think that is included in "memory used", is it?  Isn't it only data space?  After all, if we implement a maximum binary executable size, that will throttle the text size of the application.

So, I think the "sandbox" script has to:
1) If it's a java or kotlin submission, set the appropriate command line option to the java execute command (or kotlin execute command which passes it on to java).  Specfically, the -Xmx### option.
2) If its C++/C/Python, execute "ulimit -d ###" prior to executing the submission

Now, for Windows, it's a whole other story, of course.  The Windows System Resource Manager can be used for this.  Policies can be set up to do what we need: [https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc732705(v=ws.11)?redirectedfrom=MSDN](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc732705(v=ws.11)?redirectedfrom=MSDN)  We can set up a process matching criteria such as:  all applications that are started in a folder, say: "C:\user\pc2\executesite1judge1\*"  (you can use any wildcard string).
Again, for java this isn't a problem, as you can limit memory on the command line.  For C/C++/Python, a policy can be set up.
CPU Time, however, does not appear to be controllable by the Windows System Resource Manager, rather, the exising pc2 model may have to be used.
