### ISSUE TITLE
ScoreboardCommon code contains processing for XSL files, which it shouldn't be doing

### ISSUE THREAD

**Issue by clevengr** [pc2ccs/pc2v9#324]
**Describe the issue**: 
In earlier times (when JSON output was first introduced), there was XSL code (like `scoreboard.json.xsl`) which was used to generate files like `scoreboard.json`.   Over time we migrated JSON production into Java code, and stopped using the old files like `scoreboard.json.xsl` (in fact, no such file even exists any longer under pc2v9/data/xsl, which is where it used to live).  

The code in `ScoreboardCommon.generateOutput()` needs a thorough review, with an eye toward eliminating processing of things like XSL files which we no longer use.

**Comment by troy2914** [comment]
I disagree with this.  If a user wants to write json in xsl, they should be allowed.   We should **not** be removing flexibility.

**Comment by lane55** [comment]
There is no scoreboard.json.xsl in the default distribution either in data/xsl or under samps. 
I think this can be closed because only if someone adds scoreboard.json.xsl into data/xsl will
this be a problem.

To summarize this was a procedural problem that can be solved by not finding a scoreboard.json.xsl
somewhere and adding it to the xsl files.

**Comment by lane55** [comment]
Marking as invalid because this is a procedural issue/bug.

**Comment by clevengr** [comment]
Based on Troy's and Doug's comments, I'm agreeing this is procedural and the Issue isn't valid; closing.
