### ISSUE TITLE
Temporary support for command-line suppression of Connections and Logins grids on Admin.

### ISSUE THREAD

**Issue by clevengr** [pc2ccs/pc2v9#432]
**Describe the issue**: 
The ACPC 2022 Kickoff Contest died because of issues with PC2.  The contest had 3300+ teams and had received 6700+ submissions by the time it was called off.  The root issue seems to have been that the server crashed (probably due to OOM) and failed to write a large number of RunFiles to disk.  This in turn caused errors when attempts to fetch those runs were made.  At the same time, the Admin became totally unusable ("frozen") so no investigation or recovery attempts were possible.

A detailed investigation by a number of people spread across 9 time zones seems to indicate that the issue with the Admin freezing was the MCLB grids failing to handle the large number of WTI connections and logins.  Removing those two grids from the AdminView allowed a recreation of the contest to function smoothly (i.e., without the Admin locking up).

A longer-term solution needs to be found -- for example, replacing all uses of MCLB with JTables.  However, in order to get the next ACPC contest running in a few days, a workaround is to provide the ability to start the Admin without those two grids present.

**To Reproduce**: 
- Start up the ACPC 2022 Kickoff Contest on AWS, then start an Admin.  

**Expected behavior**: 
The Admin GUI should be responsive.

**Actual behavior**: 
The Admin GUI locks up (doesn't respond to input).

**Comment by lane55** [comment]
There is an existing PR (https://github.com/pc2ccs/pc2v9/pull/418)  that can address this UI load/startup problem.  This UI does not load any tab/grids by default.

Fix/Issue is #417 - loads the Reports pane by default and provides the user a way to load _any_ other pane (new and legacty Runs, Logins, Connections, etc.)

**Comment by lane55** [comment]
While this seems like a small LOE fix, I estimate it may take up to 3 hours to code and test adding the CLI option and suppressing the loading of the tabs.

Another way to fix this is to create a new UI just like the legacy UIs were created.   If that approach is
chosen then consider the existing PR (https://github.com/pc2ccs/pc2v9/pull/418) for a Report UI that has was submitted a week ago.

There seems to be an assumption that the loading of the MCLB/grids is the cause for the "slowness", whereas the processing of
all the packets may be also a cause for slowness.   The assumption may be valid if a Judge UI loads faster because it loads
most of the packet, esp Run packets, that the Admin loads.
