### ISSUE TITLE
Add support for interactive problems

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#538]
**Describe the issue**: 

Add support for interactive problems.

TODO - find specification reference for interactive problems

In the pretest contest ( https://github.com/icpcsysops/ccsconfig-dhaka/tree/master/contests/pretest) there is a 'interactive' identifier identifying that the problem is interactive (?)

config/accessdenied/problem.yaml: validation: custom interactive
config/boredombuster/problem.yaml: validation: custom interactive

**To Reproduce**: 

**Expected behavior**: 

**Actual behavior**: 

**Environment**: 

**Log Info**:  

**Screenshots**:  

**Additional context**: 

wf 2022 pretest had a interactive problem

**Comment by johnbrvc** [comment]
The following "specification" (and I use the term lightly) mentions interactive validators and how they should work. [https://icpc.io/problem-package-format/spec/output_validators?highlight=interactive#invocation](url)  It doesn't go into too many specifics.  

When this is ultimately implemented it's going to be a neat trick to have interactive validators work under Windows due to the piping of stdin and stdout that has to be set up.  There will be different code for Linux and Windows (and maybe even other versions of Unix).

**Comment by clevengr** [comment]
The judges for WF Sharm have now said that they DO expect the CCS(s) to support Interactive Problems.  For this reason it might make sense to remove the "low priority" label and bump the priority of this up a little bit.  (On the other hand, we did have a "workaround" (aka "kludge") for doing this in Dhaka and this *might* be sufficient.

**Comment by clevengr** [comment]
JohnB and JohnC had some discussions about this issue; I'm recording them here for the record and to help support further work on this issue (and in particular, trying to get going on it in order to be able to use it for WF Sharm).  Among the topics discussed were:
- We've added sandboxing with CGroups since Dhaka (and it was tested during NAC23).  This complicates the issue of interactive problems.  Specifically, the current "workaround" solution for interactive problems will have the side-effect that _the time and memory used by the interactive validator will be counted against the time and memory limits of the submission_ (which isn't the way interactive problems are supposed to work).
- We discussed two possible "solution paths" for supporting interactive problems (there may be others):
  - Clone the existing "pc2sandbox.sh" script into a new "pc2interactivesandbox.sh" script; modify the new script to accept arguments as necessary to allow it to fork two processes:  the interactive validator and the submission; have the script connect the I/O channels of those two processes as necessary to allow them to interact; make minimal modifications to the Java code so that it simply knows whether a problem is interactive or not and invokes the appropriate sandbox script.
  - Modify the Java code so that it recognizes the need to perform different I/O channel connections for interactive problems than for "regular" problems; have the Java code do all the I/O setup and fork two different processes using those I/O channels: one running the interactive validator (possibly initially just as a "standard process") and the other running the submission in a CGroup (as is currently done by the existing pc2sandbox.sh script).  
- The advantages of the first approach (separate scripts) are that it is probably less risky, because it makes fewer changes to the Java code (specifically, to Executable).   The advantages of the second approach (modifying the Java code to recognize the different requirements for I/O setup for interactive problems) are that it is more likely to be a better long-term solution -- specifically, more compatible with the eventual desire to support sandboxing (and interactive problems) in Windows.
- It might makes sense to start by tackling the _first_ approach, using it to get our collective heads around what ugly details might crop up in solving the overall issue, then once we've got a prototype working that way, use the knowledge gained to consider working on the _second_ approach.  JohnB expressed willingness to look further into this.
- _Either_ approach is at a minimum probably going to require updating the Problem class to support an _**isInteractive**_ flag, so that probably needs to be done as part of any initial effort.  This means updating not only the Problem class itself, but also updating the YAMLLoader to recognize the CLICS **validator: interactive** setting and updating the New Problem dialog to support an **isInteractive** selector (such as a checkbox).
