### ISSUE TITLE
Shadow Run Compare missing pending count

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#584]
**Is your feature request related to a problem?** 

On Shadow Run Compare does not show Pending count with
other counts.

**Feature Description**: 

Add Pending: NNN 
to show the number of pending runs. on the same line as the Total Submissions, Matches, etc. counts

**Have you considered other ways to accomplish the same thing?** 

n/a

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?**

**Additional context**:

**Comment by clevengr** [comment]
The code already contains a display of Pending Runs, in method `updateSummary()` of class `ShadowCompareRunsSummaryPane`  (around lines 157-162).   The problem is that this field is not always displayed (I've seen it displayed; I think on a Windows system); I've seen it NOT displayed, on a Linux system.  I think therefore that this is a Layout Manager issue.

In particular, the `ShadowCompareRunsSummaryPane` (which extends JPanel) has a constructor which makes the following call:  `this.setMaximumSize(new Dimension(600,40));`.  This JPanel component is placed inside another JPanel with a maximum size of 700,40.  I think the "Pending" label is probably extending beyond the 600 limit and so the FlowLayout manager is trying to move the Pending label/count to the next line -- but it won't be visible.  I think a fix would be to change the setMaximumSize(600,40) to setMaximumSize(700,40).
