### ISSUE TITLE
The results.tsv file includes teams that are not supposed to be shown on the scoreboard

### ISSUE THREAD

**Issue by johnbrvc** [pc2ccs/pc2v9#588]
Thank you for working to help us improve PC^2!  
Please fill in the following fields in order to help us understand what issue you are reporting.

**Describe the issue**:
If a team does not have the DISPLAY_ON_SCOREBOARD property set, it is still included in the results.tsv file.  It should not be. 

**To Reproduce**: 
Load a contest.
Create teams, and mark one or more as "not shown on scoreboard"
Submit some (successful) runs by teams that shown on the scoreboard.
Submit some (successful) runs by teams that are not shown on the scoreboard.
Let them get judged.
Finalize the contest.
Look at the results.tsv file.  The teams not shown on the scoreboard will be shown in the results.tsv file.

**Expected behavior**: 
Only those teams that are shown on the scoreboard should appear in the results.tsv file. 

**Actual behavior**:
Teams marked as not shown on the scoreboard appear in the results.tsv.  This can cause incorrect rankings of
teams that ARE shown on the scoreboard

**Environment**:
All.

**Log Info**:  PC^2 generates logs (in the **logs** folder for client modules; under the **profiles** folder for the PC2 Server).  Please review the relevant logs and provide copies of them as attachments -- particularly if the logs show Exceptions being thrown.  

**Screenshots**:  if applicable, please add attachments showing screenshots to help explain the issue.

**Additional context**: 
The exports/ccs/ResultsFile.java uses the NSA to generate the results.tsv.  This does not look at the shown on scoreboard permission.
[results.txt](https://github.com/pc2ccs/pc2v9/files/9957498/results.txt)

**Comment by johnbrvc** [comment]
TODO should be refactored into the DefaultScoringAlgorithm

**Comment by lane55** [comment]
Made a high priority fix because an invalid results.tsv file is produced.

**Comment by lane55** [comment]
The results.tsv uses the NSA (NewScoringAlgorithm) class.   With the fix in the PR/branch a number
of methods/features will be fixed as well.

A number of services/features are not affected because they
use the DSA ( DefaultScoringAlgorithm ).   The DSA already
handled the condition where there were teams to not be displayed
(not DISPLAY_ON_SCOREBOARD )

This change updated the NSA to not include/display teams that
should not be displayed.

-- Other features are fix with this issue/PR.

Fixes ResultsFile for this issue.
Fixed The API ScoreboardService ( /contest/scoreboard end point)  via ContestAPIStandingsJSON

ScoreboardFile - scoreboard.tsv report
And others.
