### ISSUE TITLE
Sometime the judgement event is output before submission event

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#698]
**Is your feature request related to a problem?** 

In Event Feed.

Sometime the judgement event is output before submission event

{"type":"judgements", "id":"pc2-212", "op":"update", "data": {"id":"Run--1756498373643254701","submission_id":"11","start_time":"2023-02-25T12:12:49.937-08","start_contest_time":"00:54:49.112","judgement_type_id":"AC","end_time":"2023-02-25T12:13:00-08","end_contest_time":"00:55:00.000"}}
{"type":"submissions", "id":"pc2-210", "op":"create", "data": {"id":"11","language_id":"Java--2186160493553050763","problem_id":"sumit","team_id":"6","time":"2023-02-25T12:12:49.937-08","contest_time":"00:54:49.112","files":[{"href":"/submissions/11/files"}]}}

**Feature Description**: 

Always output a submission for any the judgement, same submission id.

So for each judgement event output a corresponding submission event, like this:

{"type":"submissions", "id":"pc2-211", "op":"update", "data": {"id":"11","language_id":"Java--2186160493553050763","problem_id":"sumit","team_id":"6","time":"2023-02-25T12:12:49.937-08","contest_time":"00:54:49.112","files":[{"href":"/submissions/11/files"}]}}
{"type":"judgements", "id":"pc2-212", "op":"update", "data": {"id":"Run--1756498373643254701","submission_id":"11","start_time":"2023-02-25T12:12:49.937-08","start_contest_time":"00:54:49.112","judgement_type_id":"AC","end_time":"2023-02-25T12:13:00-08","end_contest_time":"00:55:00.000"}}

**Have you considered other ways to accomplish the same thing?** 

Yes. no way.

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?**

Add the new event in the class EventFeedStreamer

**Additional context**:

**Comment by clevengr** [comment]
I think that before the suggested addition is is made ("add the new event in the class EventFeedStreamer"), it should be verified whether the problem is that the submission event is NEVER output, or that SOMETIMES it is output AFTER the judgement event (which would not be CLICS spec compliant) but SOMETIMES it is output BEFORE the judgement event (which is what should be happening).

If the submission is received and then the server tries to send it to many judges before sending it to the Event Feed, it's possible that the first judge to receive the submission could finish judging it and send a judgement (causing the judgement to go to the event feed on a separate thread) before the submission itself gets sent to the event feed.  This would appear in the event feed as "judgement with no (previous) submission".

If this is what is happening, the correction should not be to force the EventFeedStreamer class to send a submission just because it got a judgement; the correction should be to send the submission notification to the event feed before sending it to the judge(s).

**Comment by lane55** [comment]
A hack from this branch https://github.com/lane55/pc2v9/tree/i_698_always_output_submission_before_judgement_event
was used at the Pacific NW.

**Comment by lane55** [comment]
This issue can be closed, in favor of a root cause fix in #704
