### ISSUE TITLE
Sandbox execution does not clean up straggler processes

### ISSUE THREAD

**Issue by johnbrvc** [pc2ccs/pc2v9#810]
**Describe the issue**:
If a user submission forks itself (which is in and of itself against contest policy - but, nevertheless...) and the original process is killed or otherwise goes away, the child processes can remain around and continue forking even after the sandbox has terminated.  This can jam up an autojudge (AJ) by causing future runs by that AJ to fail due to too many processes.  This was noticed when running wf46/systest0 during testing.

**To Reproduce**:
Submit and judge the Linked C program below.
[stress-test-fork-setsid.txt](https://github.com/pc2ccs/pc2v9/files/12661621/stress-test-fork-setsid.txt)

The C program forks, then creates a new session ID making it hard to keep track of and the stragglers will keep on multiplying.

**Expected behavior**: 
When a sandbox run finishes, all children should be terminated and disappear.

**Actual behavior**:
Submitting the above C code will cause straggler "./a.out" processes to linger forever, jamming up the AJ and causing random errors such as "too many processes" since the sandbox limits it by UID.

**Environment**:
Ubuntu 22.04 WF Contest Image
PC2 with sandbox support

**Log Info**:  

**Screenshots**:

**Additional context**:
`cgroupv2 `provides a way to kill of ALL process in the **cgroup**.  The sandbox scripts should use this method when they exit (See https://docs.kernel.org/admin-guide/cgroup-v2.html#:~:text=A%20write%2Donly%20single%20value,will%20be%20killed%20via%20SIGKILL.)

**Comment by clevengr** [comment]
This Issue appears to have been fixed by PR 812 ([I810 Make sure to kill off all processes in cgroup at start #812](https://github.com/pc2ccs/pc2v9/pull/812)).  It should have been closed after that PR was approved and merged.  The reason it did NOT get closed is likely that the PR comment in the PR section regarding "Issue which this PR addresses" just has `#810` in it.  In order for GitHub to automatically close an issue from a PR, the PR must contain either the word `Closes` or the word `Fixes` in front of the Issue number -- not just the Issue number by itself.

Closing the issue since the PR for it was approved and merged.
