### ISSUE TITLE
Team client GUI do not show Additional Files in the confirmation Window

### ISSUE THREAD

**Issue by SamanwaySadhu** [pc2ccs/pc2v9#897]
**Describe the issue**:
When someone tries to submit some Additional files, the Confirm Submission window does not display the additional files' paths like it shows for the main file.

**To Reproduce**:
Start a Server, Admin and Team client. Start the contest and then try to make a submission from Team GUI with some additional files.

**Actual behavior**:
![Capture](https://github.com/pc2ccs/pc2v9/assets/24360328/76ca304b-09e2-4ba8-aa3e-079e9053cb97)

**Expected behavior**:
The list of additional files' paths should also show up in the window.

**Environment**: please complete the following information:
Windows 10, Eclipse 2021-12 R, JDK 8u381 (1.8)

**Additional context**:
Probably need to update `testOrSubmitRun` function of the class `src/edu/csus/ecs/pc2/ui/SubmitRunPane.java` at this line the string [confirmQuestion](https://github.com/pc2ccs/pc2v9/blob/e1da7a679e659057fd08b1634cd0eed61af67f21/src/edu/csus/ecs/pc2/ui/SubmitRunPane.java#L495)

**Comment by johnbrvc** [comment]
This is probably more of a "feature" request than a bug (there's a separate form for Features).  However, since the issue you are working on (duplicate file names being submitted) is related to this, it might make sense to address this after you finish the other issue.  You can create a new branch for this.
